# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Packages

on:
  release:
    types: [published]
  push:
    tags:        
      - v*
    branches: [ master, dev]
  pull_request:
    branches: [ master ]
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build-src:
    name: Build Base Packages
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'haproxy/haproxy'
          ref: 'v3.1-dev9'
          path: 'haproxy'
      - run: |
          ls
      - name: Set up Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          platform: x86_64
          packages: make gcc-core gcc-g++

      # Cygwin executables are added to PATH, so you can call them directly:
      - run: |
          ls.exe -Al
          pwd.exe
      - name: Make haproxy
        run: |
          cd haproxy
          make TARGET=cygwin
      - run: |
          ls
          ls c:
          ls c:\cygwin
          ls c:\cygwin\bin
          mkdir release
          cp haproxy\haproxy.exe release
          cp C:\cygwin\bin\cygwin1.dll release
          cp C:\cygwin\bin\cyggcc_s-seh-1.dll release
          cp haproxy.cfg release
          ls release


      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: haproxyv_v3.1-dev9
          path: |
            ./release/*
            
